### ISSUE TITLE
Incorrect RIC_ResNet18 Implementation

### ISSUE THREAD

**Issue by XYPB** [HanlinMo/Rotation-Invariant-Coordinate-Convolutional-Neural-Network#2]
Hi,

I notice that the provided implementation of `RIC_ResNet18` model in the [RIC_ResNet18](https://github.com/HanlinMo/Rotation-Invariant-Coordinate-Convolutional-Neural-Network/blob/4633241b4aea04b38840e83aa187c0f08515cb81/ResNet18/RIC_ResNet18.py#L176C5-L176C17) file only have 9 individual convolutional layer, which suggests that it is only ResNet9 instead of ResNet18. And the number of parameters of this model is also only one-half of conventional ResNet18, which *should* be the same given the implementation.

I am wondering if this is a typo or intended, and also, will this influence the results presented in the paper?

Any reply is highly appreciated! Thanks in advance!

Best

**Comment by HanlinMo** [comment]
Hi! Thank you so much for spotting this issue. I have updated the RIC-ResNet18 code, and now it's correct. I believe that this minor error doesn't affect the results presented in the paper. You can try running the new code. Additionally, the new convolution operation can be combined with CNN models of any depth, and the depth of the model won't impact its rotational invariance.
